### ISSUE TITLE
tests failing on windows

### ISSUE THREAD

**Issue by radiovisual** [radiovisual/metalsmith-rootpath#3]
```
metalsmith-rootpath
    √ should set a rootPath value on Metalsmith metadata
    √ should set rootPath to empty string when file is in root directory
    1) should set rootPath to `../` on files one directory down


  2 passing (53ms)
  1 failing

  1) metalsmith-rootpath should set rootPath to `../` on files one directory dow
n:
     Uncaught TypeError: Cannot read property 'rootPath' of undefined
      at Metalsmith.<anonymous> (C:\Users\lab\Documents\GitHub\metalsmith-rootpa
th\test\index.js:43:41)
      at Immediate._onImmediate (C:\Users\lab\Documents\GitHub\metalsmith-rootpa
th\node_modules\metalsmith\node_modules\unyield\node_modules\co\index.js:52:14)
```

**Comment by radiovisual** [comment]
@jameslnewell , would you be willing to look into this?  I don't have access to a windows machine right now. The tests pass on my mac, but I just updated the code to use a faster string search implementation, and that may have made things incompatible with windows again...

It may have something to do with [line #20 on index.js](https://github.com/radiovisual/metalsmith-rootpath/blob/master/index.js#L20):

``` js
var pathslash = process.platform === 'win32' ? '\\' : '/';
```

If you have time to take a quick look, I would really appreciate it. If not, I can get around to it once I gain access to a windows machine. 

Cheers! :beer:

**Comment by jameslnewell** [comment]
Its the paths, the test is looking for `files['1.0/index.html']` which doesn't exist, but `files['1.0\\index.html']` does. Using `path.join()` instead of manually concatenating paths looks like it works.

**Comment by radiovisual** [comment]
ah. that makes perfect sense. Thanks a lot. I will update soon.

**Comment by jameslnewell** [comment]
no probs, thanks for the lib!
